# Generated by Django 5.2.8 on 2025-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Wyróżnij na stronie głównej"
            ),
        ),
    ]
