# Generated by Django 5.2.8 on 2025-12-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_product_cena_product_dla_kogo_and_more"),
    ]

    operations = [
        # First, convert existing data
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=True, verbose_name="Czy dostepny w sklepie"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cena",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cena promocyjna",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis (ang.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="dla_kogo",
            field=models.JSONField(blank=True, default=list, verbose_name="Dla kogo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="gatunek_ptakow",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Pióra zgubiły (gatunek)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kolor_pior",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Kolor piór w przewadze"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nazwa (ang.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="opis",
            field=models.TextField(blank=True, verbose_name="Opis (pl.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cena podstawowa"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Automatycznie generowane z nazwy", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Automatycznie generowane przez Stripe",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Automatycznie generowane przez Stripe",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tytul",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nazwa (pl.)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rodzaj_zapiecia",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rodzaj zapięcia"
            ),
        ),
    ]
