# Generated by Django 5.2.8 on 2025-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_product_pytanie_o_przedmiot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rodzaj_zapiecia",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rodzaj zapięcia"
            ),
        ),
    ]
