# Generated by Django 5.2.8 on 2025-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_product_dlugosc_kategoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dlugosc_kategoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("krotkie", "Krótkie"),
                    ("srednie", "Średnie"),
                    ("dlugie", "Długie"),
                    ("bardzo_dlugie", "Bardzo długie"),
                ],
                max_length=100,
                verbose_name="Długość kategoria",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kolor_elementow_metalowych",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zloty", "Złoty"),
                    ("srebrny", "Srebrny"),
                    ("mieszany", "Mieszany"),
                    ("inny", "Inny"),
                ],
                max_length=100,
                verbose_name="Kolor elementów metalowych",
            ),
        ),
    ]
