# Generated by Django 5.2.8 on 2025-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_product_dlugosc_kategoria_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Czy dostepny w sklepie"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Wyróżnij na stronie głównej"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="home_produc_created_e63807_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["active", "-created_at"], name="home_produc_active_42f5a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["featured", "-created_at"],
                name="home_produc_feature_0566ba_idx",
            ),
        ),
    ]
