# Generated by Django 5.2.8 on 2025-12-19 12:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_productimage_image"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "location",
                    models.CharField(max_length=500, verbose_name="Lokalizacja"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Data rozpoczęcia")),
                ("end_date", models.DateTimeField(verbose_name="Data zakończenia")),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktywny"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Eventy",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["-start_date"], name="home_event_start_d_e565f6_idx"
                    ),
                    models.Index(
                        fields=["active", "-start_date"],
                        name="home_event_active_9ab53f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "event",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.event",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie eventu",
                "verbose_name_plural": "Zdjęcia eventu",
            },
        ),
    ]
