# Generated by Django 6.0 on 2026-01-17 15:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_product_description_alter_product_opis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, default=" ", verbose_name="Opis (ang.)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="opis",
            field=wagtail.fields.RichTextField(
                blank=True, default=" ", verbose_name="Opis (pl.)"
            ),
        ),
    ]
