# Generated by Django 6.0 on 2026-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_event_external_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dlugosc_kategoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("krotkie", "Krótkie (do 10cm)"),
                    ("srednie", "Średnie (10-15cm)"),
                    ("dlugie", "Długie (15-20cm)"),
                    ("bardzo_dlugie", "Bardzo długie (20cm+)"),
                ],
                default="",
                max_length=255,
                verbose_name="Długość kategoria",
            ),
        ),
    ]
