# Generated by Django 6.0 on 2026-03-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_product_status_reservation_reservedproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Kod który wpisuje klient, np. SUMMER20",
                        max_length=50,
                        unique=True,
                        verbose_name="Kod promocyjny",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        max_length=10,
                        verbose_name="Typ zniżki",
                    ),
                ),
                (
                    "percent_off",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Np. 20 dla 20% zniżki",
                        null=True,
                        verbose_name="Zniżka procentowa",
                    ),
                ),
                (
                    "amount_off",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Np. 2000 dla 20 PLN zniżki",
                        null=True,
                        verbose_name="Zniżka kwotowa (w groszach)",
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Puste = bez limitu",
                        null=True,
                        verbose_name="Maksymalna liczba użyć",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data wygaśnięcia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "times_redeemed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Synchronizowane ze Stripe",
                        verbose_name="Liczba użyć",
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe Coupon ID"
                    ),
                ),
                (
                    "stripe_promotion_code_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe Promotion Code ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kupon promocyjny",
                "verbose_name_plural": "Kupony promocyjne",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="home_coupon_code_a982c2_idx"),
                    models.Index(
                        fields=["status"], name="home_coupon_status_fc48bc_idx"
                    ),
                ],
            },
        ),
    ]
