# Generated by Django 6.0 on 2026-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Np. 'Dom', 'Biuro', 'Paczkomat przy sklepie'",
                        max_length=100,
                        verbose_name="Nazwa",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Np. 'Mickiewicza 15'",
                        max_length=255,
                        verbose_name="Ulica i numer",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        help_text="Np. '00-001'",
                        max_length=10,
                        verbose_name="Kod pocztowy",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Miasto")),
                (
                    "point",
                    models.CharField(
                        blank=True,
                        help_text="Kod paczkomatu/punktu np. 'ADA01N' dla InPost",
                        max_length=50,
                        verbose_name="Kod punktu (opcjonalnie)",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Domyślny punkt odbioru"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktywny")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Punkt odbioru",
                "verbose_name_plural": "Punkty odbioru",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AlterField(
            model_name="coupon",
            name="amount_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Np. 20 dla 20 PLN zniżki",
                max_digits=10,
                null=True,
                verbose_name="Zniżka kwotowa (PLN)",
            ),
        ),
    ]
