# Generated by Django 6.0 on 2026-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_add_pickup_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="InPostPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Np. 'ADA01N'",
                        max_length=50,
                        unique=True,
                        verbose_name="Kod paczkomatu",
                    ),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Ulica")),
                (
                    "building_number",
                    models.CharField(max_length=20, verbose_name="Numer budynku"),
                ),
                (
                    "postcode",
                    models.CharField(max_length=10, verbose_name="Kod pocztowy"),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Miasto"
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Szerokość geograficzna")),
                ("longitude", models.FloatField(verbose_name="Długość geograficzna")),
                (
                    "location_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Opis lokalizacji"
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Godziny otwarcia"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktywny"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paczkomat InPost",
                "verbose_name_plural": "Paczkomaty InPost",
                "ordering": ["city", "name"],
                "indexes": [
                    models.Index(fields=["city"], name="home_inpost_city_bb498c_idx"),
                    models.Index(
                        fields=["active"], name="home_inpost_active_acd85d_idx"
                    ),
                    models.Index(fields=["name"], name="home_inpost_name_360023_idx"),
                ],
            },
        ),
    ]
