# Generated by Django 6.0 on 2026-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_add_inpost_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrevoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="Email nadawcy"),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=255, verbose_name="Nazwa nadawcy"),
                ),
                (
                    "thank_you_template_id",
                    models.IntegerField(
                        help_text="ID szablonu email po zakupie",
                        verbose_name="ID szablonu 'Dziękujemy'",
                    ),
                ),
                (
                    "shipping_template_id",
                    models.IntegerField(
                        help_text="ID szablonu email przy wysyłce",
                        verbose_name="ID szablonu 'Wysyłka'",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfiguracja Brevo",
                "verbose_name_plural": "Konfiguracja Brevo",
            },
        ),
        migrations.CreateModel(
            name="FurgonetkaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sandbox",
                    models.BooleanField(
                        default=True,
                        help_text="Używaj środowiska testowego",
                        verbose_name="Tryb sandbox",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="Client ID"),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=255, verbose_name="Client Secret"),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Email / Username"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Hasło")),
                (
                    "sender_name",
                    models.CharField(max_length=255, verbose_name="Nazwa nadawcy"),
                ),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="Email nadawcy"),
                ),
                (
                    "sender_phone",
                    models.CharField(max_length=20, verbose_name="Telefon nadawcy"),
                ),
                (
                    "sender_street",
                    models.CharField(max_length=255, verbose_name="Ulica nadawcy"),
                ),
                (
                    "sender_city",
                    models.CharField(max_length=100, verbose_name="Miasto nadawcy"),
                ),
                (
                    "sender_postcode",
                    models.CharField(
                        max_length=10, verbose_name="Kod pocztowy nadawcy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfiguracja Furgonetka",
                "verbose_name_plural": "Konfiguracja Furgonetka",
            },
        ),
        migrations.CreateModel(
            name="FurgonetkaService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Np. 'inpost', 'dpd', 'poczta'",
                        max_length=50,
                        unique=True,
                        verbose_name="Nazwa usługi",
                    ),
                ),
                (
                    "service_id",
                    models.CharField(
                        help_text="ID usługi z Furgonetka (np. '11361412')",
                        max_length=20,
                        verbose_name="Service ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Opis"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktywna")),
            ],
            options={
                "verbose_name": "Usługa Furgonetka",
                "verbose_name_plural": "Usługi Furgonetka",
                "ordering": ["name"],
            },
        ),
    ]
