# Generated by Django 6.0 on 2026-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_brevoconfig_furgonetkaconfig_furgonetkaservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Session ID",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email klienta"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Imię klienta"
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        help_text="Np. 'InPost Paczkomat', 'Kurier DPD'",
                        max_length=100,
                        verbose_name="Metoda dostawy",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True,
                        help_text="Adres lub punkt odbioru",
                        verbose_name="Adres dostawy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sold", "Sprzedane"), ("sent", "Wysłane")],
                        db_index=True,
                        default="sold",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Wypełnij przy zmianie statusu na 'Wysłane'",
                        max_length=100,
                        verbose_name="Numer śledzenia",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True,
                        help_text="Np. 'inpost', 'dpd'",
                        max_length=50,
                        verbose_name="Przewoźnik",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kwota (PLN)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="transactions",
                        to="home.product",
                        verbose_name="Produkty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transakcja",
                "verbose_name_plural": "Transakcje",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="home_transa_status_b3737d_idx"
                    ),
                    models.Index(
                        fields=["customer_email"], name="home_transa_custome_b63169_idx"
                    ),
                ],
            },
        ),
    ]
