# Generated by Django 6.0 on 2026-03-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_add_transaction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="brevoconfig",
            name="newsletter_list_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID listy kontaktów w Brevo dla subskrybentów newslettera",
                null=True,
                verbose_name="ID listy newsletter",
            ),
        ),
    ]
