# Generated by Django 6.0 on 2026-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_add_newsletter_list_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Punkt nadania', 'verbose_name_plural': 'Punkty nadania'},
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Domyślny punkt nadania'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='point',
            field=models.CharField(blank=True, help_text="Kod paczkomatu/punktu np. 'ADA01N' dla InPost. Wymagany — bez kodu Furgonetka tworzy przesyłkę z odbiorem kuriera pod adres.", max_length=50, verbose_name='Kod punktu (opcjonalnie)'),
        ),
    ]
