# Generated by Django 5.2.8 on 2025-12-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_product_active_alter_product_cena_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pytanie_o_przedmiot",
        ),
    ]
