# Generated by Django 6.0 on 2026-01-17 14:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_event_eventimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Opis (ang.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="opis",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Opis (pl.)"),
        ),
    ]
