# Generated by Django 6.0 on 2026-02-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_product_sold_at_product_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name": "Rezerwacja",
                "verbose_name_plural": "Rezerwacje",
                "ordering": ["-reserved_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="home_reserv_expires_c5d8e8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="home_reserv_status_9e6d62_idx"
                    ),
                    models.Index(
                        fields=["-reserved_at"], name="home_reserv_reserve_3d6007_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReservedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="home.product",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_products",
                        to="home.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zarezerwowany produkt",
                "verbose_name_plural": "Zarezerwowane produkty",
                "ordering": ["reservation", "added_at"],
                "unique_together": {("reservation", "product")},
            },
        ),
    ]
